config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  # FLOW RENTER
  resources :watches, only: [:index, :show]
  resources :shops,   only: [:show]

  resources :bookings, only: [:index, :show] do
    resources :booking_items, only: [:create]
  end
  get 'basket', to:'bookings#basket', as: :basket
  # resources :booking_items, only: [:destroy]

  resource :dashboard, only: [:show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :watches do
    resources :booking_items, only: [:destroy]
  end

  # wishlist
  resources :watches, only: [] do
    resources :bookmarks, only: [:index, :new, :create]
  end
  resources :bookmarks, only: [:destroy]

  # get '/dashboard', to: 'dashboards#show'

  # FLOW OWNER (si on a le temps)
  # namespace :owner do
  #   resources :shops
  #   resources :watches
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_many :booking_items
  has_many :watches, through: :booking_items
  monetize :price_cents
end

app/models/booking_item.rb
class BookingItem < ApplicationRecord
  include CloudinaryHelper
  belongs_to :booking
  belongs_to :watch
  has_many :reviews, dependent: :destroy

  after_create_commit :compute_cost
  monetize :cost_cents

  def stripe_line_item
    {
      name: watch.sku,
      images: [cloudinary_url(watch.photo.key)],
      amount: cost_cents,
      currency: 'eur',
      quantity: 1
    }
  end


  private

  def compute_cost
    price = watch.cost_per_day_cents
    self.cost_cents = (end_date - start_date).to_i * price
    save
  end

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :watch
  validates :user_id, presence: true
  validates :watch_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  monetize :price_cents, currency: { present: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking_item
  belongs_to :user
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :watches, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :orders
  has_one_attached :photo
  has_many :bookmarks

  def get_items
    self.bookings.find_by(status: 'pending').booking_items.count
  end

 

end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :shop
  has_one_attached :photo
  has_many :booking_items
  has_many :bookings, through: :booking_items
  has_many :bookmarks


    include PgSearch::Model
  pg_search_scope :search_by_model_and_brand,
    against: [:model, :brand],
    using: {
      tsearch: { prefix: true }
    }
  monetize :cost_per_day_cents
  monetize :price_cents
end

# rails g model Order state:string watch_sku:string amount:monetize checkout_session_id:string user:references watch:references

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_booking

  def set_booking
    @booking = if Booking.where(status:'pending', user: current_user).exists?
                  Booking.find_by(status:'pending', user: current_user)
               else
                 Booking.create(status:'pending', user: current_user)
               end
  end
end

app/controllers/booking_items_controller.rb
class BookingItemsController < ApplicationController
  before_action :authenticate_user!
  def create
    @booking = Booking.find params[:booking_id]
    @booking_item = BookingItem.new(booking_item_params)
    @booking_item.booking = @booking
    if @booking_item.save
      update_booking_price
      redirect_to watches_path
    end
  end

  def show
    @booking_item = BookingItem.find(params[:id])
    @watch = Watch.find(params[:watch_id])
  end

  def destroy
    @booking_item = BookingItem.find(params[:watch_id])
    @booking_item.destroy
    update_booking_price
    flash[:notice] = "Votre montre a bien été supprimée"
    redirect_to booking_path(@booking)
  end

  private

  def booking_item_params
    params.require(:booking_item).permit(:watch_id, :start_date, :end_date)
  end

  def update_booking_price
    @booking.price_cents = @booking.booking_items.reduce(0) { |sum, item| sum + item.cost_cents}
    @booking.save
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
    @booking_items = @booking.booking_items # array with all bookings item for current user
  end

  def basket
    @bookings = Booking.where(status:'pending', user_id: current_user.id)
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @watch = Watch.find(params[:watch_id])
    @bookmark = Bookmark.new(watch: @watch, user: current_user)
    if @bookmark.save
      flash[:notice] = "Votre montre #{@watch.brand} a bien été ajoutée dans vos favoris"
      redirect_to @watch
    else
      render 'watch/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    flash[:notice] = "Votre montre a bien été supprimée "
    redirect_to dashboard_path
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @bookings = current_user.bookings
    if params[:status].present?
      @bookings = @bookings.where(status: params[:status])
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    booking = Booking.find(params[:booking_id])
    order  = Order.create!(booking: booking, price: booking.price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: booking.booking_items.map{ |bi| bi.stripe_line_item },
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
    @booking_items = @booking.booking_items # array with all bookings item for current user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @watches = Watch.all.first(4)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def show
    @shop = Shop.find(params[:id])
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  def index
    if params[:query].present?
      @watches = Watch.search_by_model_and_brand(params[:query])
    else
       @watches = Watch.all
    end
  end

  def show
    @watch = Watch.find(params[:id])
    @booking_item = BookingItem.new(watch: @watch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/basket.html.erb
<H1>Panier</H1>

<% @bookings.each do |booking| %>
<%= booking.user.name %>
<%= booking.status %>



<!-- Afficher les booking items et pas les bookings
 -->

<!--     t.bigint "booking_id"
    t.bigint "watch_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.date "end_date"
    t.date "start_date"
    t.string "status" -->

app/views/bookings/index.html.erb
<H1>Historique des paniers</H1>
<div class="container mt-5">
    <div class="book">
      <% @bookings.each do |booking| %>
        <div><%= link_to "Booking #{booking.id}", booking_path(booking) %></div>
      <% end %>
    </div>
</div>
<raise>

app/views/bookings/show.html.erb
 <div class="fond-jaune">
        <h1 class="text-center" style="color: white;">Voici votre réservation !</h1>

  <div class="container-booking">
    <div class="d-flex justify-content-between">
      <h1 id="couleur_titre">Panier</h1>
      <h2><%= @booking.price.to_i %>€</h2>
      <%= form_tag orders_path do %>
        <%= hidden_field_tag 'booking_id', @booking.id %>
        <%= submit_tag 'Paiement', class: 'float-right btn btn-flat' %>
      <% end %>
    </div>
    <br/>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Photo</th>
          <th scope="col">Montre</th>
          <th scope="col">Modèle</th>
          <th scope="col">Période</th>
          <th scope="col">Prix</th>
          <th scopre="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @booking_items.each_with_index do |item, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= cl_image_tag item.watch.photo.key, height: 40, width: 50, crop: :fill %></td>
            <td><%= item.watch.brand %></td>
            <td><%= item.watch.model.truncate_words(1) %></td>
            <td><%= item.created_at.strftime("%d %b %Y") %> | <%= item.end_date.strftime("%d %b %Y") %></td>
            <td><%= item.cost.to_i %> €</td>
            <td><%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, watch_booking_item_path(item), method: :delete, data: {confirm: "Êtes-vous sur de vouloir supprimer cette montre ?"}, class:'btn' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="banner-dashboard" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "banner-dashboard.jpg", height: 200, width: 1080 %>')">
  <div class="container">
    <p class="banner-dashboard-text"> Tableau de bord</p>
  </div>
</div>

<div class="container container-dashboard">
  <div class="row profile" display="flex">
    <div class="col-md-3 mt-0">
      <div class="profile-sidebar">
            <!-- SIDEBAR USERPIC -->

            <div class="profile-userpic row justify-content-center" >
              <%= image_tag current_user.photo, crop: :fill if current_user.photo.attached? %>
            </div>
            <!-- END SIDEBAR USERPIC -->
            <!-- SIDEBAR USER TITLE -->
            <div class="profile-usertitle">
              <div class="profile-usertitle-name">
              </div>
            </div>
            <!-- END SIDEBAR USER TITLE -->
            <!-- SIDEBAR BUTTONS -->

            <div class="profile-userbuttons">
                <p><%= current_user.name %></p>

              <%= link_to 'Les montres', watches_path, class:"btn btn-flat m-2" %>


            </div>
                 <div class="portlet light bordered">
                                                      <!-- STAT -->
                <div class="row list-separated profile-stat">

                </div>
                <!-- END STAT -->
          <div>
            <h6 class="profile-desc-title text-center">A propos de moi</h6>
            <p class="profile-desc-title text-center" id="ptext">Passionné de belles montres, <br>j'aime tout ce qui touche à l'horlogerie.</p>
            <!-- <span class="profile-desc-text pl-3"><%= current_user.description %></span> -->
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="profile-content">
        <div class="container mt-5 search-row">
          <h1>Mes commandes</h1>
              <%= form_tag dashboard_path, method: :get do %>
                <%= select_tag :status, options_for_select(['Select a status','pending', 'paid']),
                  class: "form-control"
                %>


                <%= submit_tag "Rechercher", class: "btn btn-dark button-dashboard" %>

              <% end %>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Statut</th>
                <th scope="col">Prix</th>
                <th scope="col">Période</th>
                <th scope="col">Produit</th>
                <th scope="col">Détails</th>
              </tr>
            </thead>
            <tbody>
              <% @bookings.each_with_index do |b, index| %>
                <tr class="<%= b.status %>">
                <% if b.booking_items.count != 0 %>

                  <td>
                    <% if b.status == 'pending' %>
                      <%= "🔴" %>
                    <% else %>
                      <%= "🔵" %>
                    <% end %>
                  </td>

                <% unless b.booking_items.empty? %>
                  <td><%= @booking.price.to_i %>€ </td>
                <% end %>


                <% if b.booking_items.first.start_date != nil %>
                  <td><%= b.booking_items.first.start_date.strftime("%d %b %Y") %> | <%= b.booking_items.first.end_date.strftime("%d/%m/%Y") %></td>
                <% else %>
                <% end %>

                <td>
                  <%= b.booking_items.count  %>
                </td>

                <td>
                  <button type="button" class="btn btn-dark btn-details" data-toggle="modal" data-target="#modal-<%= b.id %>">
                    Voir détails
                  </button>
                </td>
              <!-- Modal -->


                  <div class="modal fade" id="modal-<%= b.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel"></h5>
                          <div class="modal-body">
                              <% key = "collapse#{b.id}" %>

                              <div  id='<%= key %>' >
                                <div class="card-body">

                                  <% b.watches.each do |watch| %>
                                  <li>
                                    <strong><%= watch.brand %></strong>
                                  </li>
                                  <%= watch.model %>
                                  <% end %>

                                </div>
                                <br>

                                <% if b.status == 'pending' %>
                                  <%= link_to'Voir panier', booking_path(@booking), class:"btn basket btn-dark btn-sm m-2 btn-modal" %>
                                <% end %>
                              </div>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

          <!-- Fin Modal -->
                <% end %>
              </div>
              </tr>
                <% end %>
            </tbody>
          </table>
        </div>


        <div class="container mt-5">
          <h1>Commentaires</h1>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">
                  <div class="media text-muted pt-3">
                      <%= image_tag "https://avatars2.githubusercontent.com/u/54837955?v=4", class: "avatar-bordered mr-3", alt: "avatar-bordered" %>
                      <p class="media-body pb-3 mb-0 small lh-125">
                        <strong class="d-block text-gray-dark">@Muriel | Champs d'Or</strong>
                        <%= current_user.name %> est un bon client ! Il est revenu deux fois pour louer la même montre IWC
                      </p>
                    </div>
                </th>
                <th scope="col">
                  <div class="media text-muted pt-3">
                      <%= image_tag "https://res.cloudinary.com/anniou/image/upload/v1575040494/NTmAjBZhKjdHvRw2iZ2cyfkz.jpg", class: "avatar-bordered mr-3", alt: "avatar-bordered" %>
                      <p class="media-body pb-3 mb-0 small lh-125">
                        <strong class="d-block text-gray-dark">@Bernard | Horloger Paris Premium</strong>
                        <%= current_user.name %> a rendu la montre sans aucune égratinure ! Un client sérieux .
                      </p>
                    </div>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
              </tr>
            </tbody>
          </table>
        </div>
          <div class="container mt-5">
          <h1>Mes favoris</h1>
          <table class="table">
            <thead>
              <tr>
                  <% current_user.bookmarks.each do |bookmark| %>
                <th scope="col">
                    <div class="media text-muted pt-3">
                        <%= link_to watch_path(bookmark.watch) do %>
                          <%= cl_image_tag bookmark.watch.photo.key, class: "avatar-bordered mr-3", height: 46, width: 40 %>
                        <% end %>
                              <p class="media-body pb-3 mb-0 small lh-125">
                                <strong class="d-block font-weight-bold">
                                  <%= bookmark.watch.brand %> </strong>
                                  <%= bookmark.watch.price %> €
                                <%= link_to '<i class="far fa-times-circle"></i>'.html_safe, bookmark_path(bookmark), method: :delete, data: {confirm: "Êtes-vous sur de vouloir supprimer la montre ?"}%>
                              </p>
                      </div>

                      <% end %>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "banner-home.jpg", height: 200, width: 1080 %>')">

  <div class="container-home text-center">
    <h1>GOLD WATCH
    <br>La montre parfaite en toute occasion.</h1>

    <%= link_to 'Voir les montres', watches_path, class:'btn btn-low' %>
  </div>
</div>

<!-- PRESENTATION -->
<div class="container mt-5">
      <section class="features-block">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-12 text-center">
              <h1>GOLD WATCH</h1>
              <p class="lead">Comment ça marche ?</p>
            </div>
          </div>

          <div class="row text-left mt-5">
            <div class="col-12 col-sm-8 col-md-4 col-lg-3 m-sm-auto mr-md-auto ml-md-0">
              <%= image_tag "home-images/searching.svg", width: 230 %>
              <h3><strong>1 - Recherchez votre montre</strong></h3>
              <p>Nous proposons une large gamme de montres de luxe. Choisissez parmi des marques iconiques comme IWC, Tag Heuer, Rolex ...</p>
            </div>

            <div class="col-12 col-sm-8 col-md-4 col-lg-3 m-sm-auto pt-5 pt-md-0">
              <%= image_tag "home-images/rent.svg", width: 230 %>
              <h3><strong>2 - Louez votre montre</strong></h3>
              <p> La location de montres de luxe n'a jamais été aussi simple avec Gold watch ! En quelques clics, réservez votre montre et profitez en pleinement.</p>
            </div>

            <div class="col-12 col-sm-8 col-md-4 col-lg-3 m-sm-auto ml-md-auto mr-md-0 pt-5 pt-md-0">
              <%= image_tag "home-images/horloger.svg", width: 230 %>
              <h3><strong>3 - Récupérez chez l'horloger</strong></h3>
              <p>Notre réseau d'horlogers réparti dans tout Paris, va vous permettre d'aller récupérer votre montre chez un spécialiste.</p>
            </div>
          </div>
        </div>
      </section>
</div>
<!-- FIN PRESENTATION -->

<!-- CAROUSEL WATCHES -->
<div class="watches-home">
  <div class="container mt-5">
      <h2>Les montres disponibles </h2>
      <hr>
    <div class="cards-watches-home">
      <% @watches.each do |watch| %>
      <%= link_to watch_path(watch) do %>
        <div class="card d-flex justify-content-around align-items-center pt-3 text-center">
          <%= cl_image_tag watch.photo.key, height: 200, width: 210, crop: :fill %>
          <div class="card-body">
            <p class="card-text1"><%= watch.brand %></p>
            <p class="card-text2"><%= watch.model.truncate_words(2) %><br/></p>
              <small class="card-text3 text-muted"><%= watch.price %> € | Prix de vente</small>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="boutton-home d-flex justify-content-center pt-4">
          <%= link_to 'Voir les montres', watches_path, class:'btn btn-low' %>
    </div>
  </div>
</div>


<!-- FIN CAROUSEL WATCHES -->

<div class="chome">
    <div class="banner-features" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "banner-features.jpg", height: 500, width: 1030 %>')">
    <div class="container">
            <h3><strong>Ils nous font confiance</strong></h3>
              <div class="company d-flex justify-content-center">
              <%= image_tag 'companies/iwc-white.png', width:'100', class:'m-5' %>
              <%= image_tag 'companies/audmards-piguet-white.png', width:'100', class:'m-5'  %>
              <%= image_tag 'companies/omega-white.png', width:'100', class:'m-5'  %>
              <%= image_tag 'companies/rolex-white.png', width:'100', class:'m-5'  %>
              <%= image_tag 'companies/tag-heuer-white.png', width:'100', class:'m-5'  %>
              <%= image_tag 'companies/tissot-white.png', width:'100', class:'m-5' %>
            </div>
    </div>
</div>
</div>

app/views/payments/new.html.erb
<div class="container-checkout">
   <h1 class="page-title">Récapitulatif de la commande</h1>
    <article class="receipt">
      <section class="receipt__half upper">
        <p>Total à payer</p>
        <h1><strong><%= humanized_money_with_symbol @order.price_cents/100 %></strong></h1>
        <p class="sm"><strong>Edité le </strong><%= DateTime.now.strftime("%d/%m/%y - %H:%M")%></p>
        <section class="receipt">
              <button class="btn btn-flat btn-lg" style="margin-top: 35px;" id="pay">Payer</button>
                   <script src="https://js.stripe.com/v3/"></script>
                   <script>
                            const paymentButton = document.getElementById('pay');
                            paymentButton.addEventListener('click', () => {
                              const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
                              stripe.redirectToCheckout({
                                sessionId: '<%= @order.checkout_session_id %>'
                              });
                            });
                    </script>
          </section>
        <div class="receipt__content">

        </div>
      </section>

    </article>
</div>

app/views/watches/index.html.erb
<div class="searchbar-div">
    <%= form_tag watches_path, class:"form-inline my-2 my-lg-0", id:"search_field", method: :get do %>
      <%= text_field_tag :query,
      params[:query], style:'width: 600px; height: 51px;',
      class: "form-control",
      type: "search",
      placeholder: "ex. : Rolex Submariner..." %>
      <%= submit_tag 'Rechercher', class: "btn btn-low" %>
  <% end %>
</div>

<div class="container">
  <div class="cards">
    <% @watches.each do |watch| %>
    <%= link_to watch_path(watch) do %>
      <div class="card d-flex justify-content-around align-items-center pt-3 text-center">
        <%= cl_image_tag watch.photo.key, height: 200, width: 210, crop: :fill %>
        <div class="card-body ">
          <p class="card-text1 "><%= watch.brand %></p>
          <p class="card-text2 "><%= watch.model.truncate_words(2) %><br/></p>
          <p class="card-text3 "><%= watch.cost_per_day %> €/jour</p>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/watches/show.html.erb
<div class="searchbar-div">
    <%= form_tag watches_path, class:"form-inline my-2 my-lg-0", id:"search_field", method: :get do %>
      <%= text_field_tag :query,
      params[:query], style:'width: 600px; height: 51px;',
      class: "form-control",
      type: "search",
      placeholder: "ex: Rolex Submariner ..." %>

      <%= submit_tag 'Rechercher', class: "btn btn-low" %>
  <% end %>
</div>



<div class="container">
      <div class="card">
      <div class="card-body row ">
          <div class="col-sm-12 col-md-6" id="image-container">
                <div id="main-img">
                     <%= cl_image_tag @watch.photo.key, height: 500, width: 400, crop: :fill %>
              </div>
              <!-- Wishlist -->
              <% if !current_user.bookmarks.pluck(:watch_id).include?(@watch.id) %>
                <%= link_to watch_bookmarks_path(@watch), method: :post do %>
                  <span id="favorite-button" class="btn"><i class="fa fa-heart grey-heart"></i></span>
                <% end %>
              <% else %>
                  <span id="favorite-button" class="btn"><i class="fa fa-heart red-heart"></i></span>
              <% end %>
              <!-- END Wishlist -->
          </div>
          <div class="col-sm-12 col-md-6" id="product-information">
             <h2 class="p-0 m-0" id="product-title"><%= @watch.brand %></h2>
              <span id="product-short"><small><%= @watch.model %></small></span>
              <hr class="divider-featurette">
            <div class="container-fluid">
                          <div class="row">
                            <span id="old-price" class="text-danger"></span><h5 id="price"><%= @watch.cost_per_day %> €/jour</h5>
                            </div>
                            <div class="row">
                              <span class="prixvente"><%= @watch.price %> € | Prix de vente</span>
                            </div>


            </div>
             <div id="product-variables">
                 <p><%= @watch.description %></p>

                 <div id="text">

                 </div>
             </div>

                <hr class="divider-featurette">
<div id="add-to-cart">
            <%= simple_form_for([@booking, @booking_item]) do |f| %>
              <%= f.input :watch_id, as: :hidden %>
              <div class="duration-location">
                <h2>Période de location</h2>
                <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"}, label: false, placeholder: "Début de location" %>
                <%= f.input :end_date, as: :string, label: false, placeholder: "Fin de location" %>
                </div>
              </div>
              <hr class="divider-featurette">
              <%= f.submit 'Ajouter au panier', class: "btn-panier btn btn-flat"  %>
            <% end %>
          </div>
        </div>

          </div>
      </div>
  </div> <!-- end card -->
</div>




<div class="container-watch">
    <div class="col">
            <h2 style="color:white" class="text-center">Voulez-vous faire partie de notre réseau ?</h2><br/>
            <p style="color:white" class="text-center">Près de 150 horlogers nous font confiance pour louer leurs montres de luxe</p>
              <button class="btn btn-low-2">En savoir plus </button>
    </div>
</div>

<div class="container">
    <h1 class="text-center pt-5">Votre magasin :</h1>
  <div class="card">
  <div class="card-body row ">
          <div class="col-sm-12 col-md-6" id="image-container">
                <div id="main-img">
                    <%= image_tag 'map.png', width: 400, class:'m-3'%>
              </div>
              <div class="container-fluid">
                  <div class="row mx-auto" id="thumbnail-container">
                       <p><strong>Adresse :</strong> <%= @watch.shop.address %></p>
                  </div>
              </div>
          </div>
          <div class="col-sm-12 col-md-6" id="product-information">
             <h2 class="p-0 m-0" id="product-title"><%= @watch.shop.name %></h2>
              <span id="product-short"><small>
Boutique de Montres et bijoux de luxe : Horlogerie, Joaillerie</small></span>
            <div class="container-fluid">
                          <div class="row">


                          </div>
            </div>
             <div id="product-variables">
                 <p>Expert depuis plus de 50 ans dans ce domaine, ce magasin spécialisé dans l'horlogerie saura vous proposer la montre parfaite pour votre évènement.</p>

                 <div id="text">

                 </div>
             </div>

               <div id="add-to-cart" class="">

                   <button class="btn btn-flat"> <%=link_to "En savoir plus" %></button>

               </div>


              </div>
    </div>
  </div>
</div>


</div> <!-- end container-->
  </div> <!-- end card -->
</div> <!-- end container-->